/**
 * Auto-generated by SmartBank AI Codegen
 * Source: codegen/schemas/loan.schema.yaml
 * Entity: Loan
 * DO NOT EDIT MANUALLY — regenerate from YAML schema.
 */

const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const loanSchema = new mongoose.Schema(
  {
    loan_id: {
      type: String,
      unique: true,
      // External unique identifier (auto-generated UUID)
    },
    user_id: {
      type: String,
      required: [true, 'user_id is required'],
      index: true,
      // Reference to the owning user
    },
    loan_type: {
      type: String,
      required: [true, 'loan_type is required'],
      enum: ["home","car","personal","education"],
      // Type of loan
    },
    loan_amount: {
      type: Number,
      required: [true, 'loan_amount is required'],
      min: 1000,
      // Principal loan amount in INR
    },
    interest_rate: {
      type: Number,
      required: [true, 'interest_rate is required'],
      min: 0,
      // Annual interest rate in percentage
    },
    tenure: {
      type: Number,
      required: [true, 'tenure is required'],
      min: 1,
      // Loan tenure in months
    },
    emi: {
      type: Number,
      min: 0,
      // Calculated EMI (auto-computed from amount, rate, tenure)
    },
    total_payable: {
      type: Number,
      // Total amount payable (emi × tenure)
    },
    total_interest: {
      type: Number,
      // Total interest payable
    },
    status: {
      type: String,
      enum: ["pending","approved","rejected","disbursed","closed"],
      default: "pending",
      // Loan application status
    },
    bank_name: {
      type: String,
      // Preferred bank for the loan
    },
    applied_at: {
      type: Date,
      // Date of application
    },
    notes: {
      type: String,
      maxlength: 500
    }
  },
  {
    timestamps: true,   // auto-manages createdAt & updatedAt — do NOT re-declare above
    collection: 'loans',
  }
);

// ── Indexes ───────────────────────────────────────────────────────────────────
// (user_id indexed via index:true above — no explicit index needed)

// ── Hooks ─────────────────────────────────────────────────────────────────────


const Loan = mongoose.model('Loan', loanSchema);
module.exports = Loan;
