/**
 * Auto-generated by SmartBank AI Codegen
 * Source: codegen/schemas/forex.schema.yaml
 * Entity: ForexTransfer
 * DO NOT EDIT MANUALLY — regenerate from YAML schema.
 */

const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const forextransferSchema = new mongoose.Schema(
  {
    transfer_id: {
      type: String,
      unique: true,
      // External unique identifier (auto-generated UUID)
    },
    user_id: {
      type: String,
      required: [true, 'user_id is required'],
      index: true,
      // Reference to the owning user
    },
    amount: {
      type: Number,
      required: [true, 'amount is required'],
      min: 1,
      // Source amount to convert
    },
    from_currency: {
      type: String,
      required: [true, 'from_currency is required'],
      maxlength: 3,
      // Source currency ISO code (e.g. INR)
    },
    to_currency: {
      type: String,
      required: [true, 'to_currency is required'],
      maxlength: 3,
      // Target currency ISO code (e.g. USD)
    },
    exchange_rate: {
      type: Number,
      required: [true, 'exchange_rate is required'],
      min: 0,
      // Effective exchange rate at time of transfer
    },
    converted_amount: {
      type: Number,
      min: 0,
      // Auto-computed result (amount × exchange_rate)
    },
    status: {
      type: String,
      enum: ["initiated","completed","failed","cancelled"],
      default: "initiated",
      // Transfer lifecycle status
    },
    transferred_at: {
      type: Date,
      // Timestamp of transfer initiation
    },
    notes: {
      type: String,
      maxlength: 300
    }
  },
  {
    timestamps: true,   // auto-manages createdAt & updatedAt — do NOT re-declare above
    collection: 'forex_transfers',
  }
);

// ── Indexes ───────────────────────────────────────────────────────────────────
// (user_id indexed via index:true above — no explicit index needed)

// ── Hooks ─────────────────────────────────────────────────────────────────────


const ForexTransfer = mongoose.model('ForexTransfer', forextransferSchema);
module.exports = ForexTransfer;
