/**
 * Auto-generated by SmartBank AI Codegen
 * Source: codegen/schemas/card.schema.yaml
 * Entity: Card
 * DO NOT EDIT MANUALLY — regenerate from YAML schema.
 */

const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const cardSchema = new mongoose.Schema(
  {
    card_id: {
      type: String,
      unique: true,
      // External unique identifier (auto-generated UUID)
    },
    bank_name: {
      type: String,
      required: [true, 'bank_name is required'],
      index: true,
      // Issuing bank name
    },
    card_name: {
      type: String,
      required: [true, 'card_name is required'],
      // Card product name (e.g. HDFC Regalia)
    },
    card_type: {
      type: String,
      enum: ["credit","debit","prepaid"],
      default: "credit",
      // Type of card
    },
    annual_fee: {
      type: Number,
      default: 0,
      min: 0,
      // Annual fee in INR (0 = lifetime free)
    },
    joining_fee: {
      type: Number,
      default: 0,
      min: 0,
      // One-time joining fee in INR
    },
    cashback_rate: {
      type: Number,
      min: 0,
      // Cashback or reward rate percentage
    },
    benefits: {
      type: String,
      // Comma-separated benefits list (e.g. Lounge Access, Fuel Surcharge Waiver)
    },
    card_category: {
      type: String,
      enum: ["shopping","travel","fuel","lifestyle","business","student","basic"],
      // Primary use category for AI card recommendations
    },
    rating: {
      type: Number,
      min: 0,
      // Card rating out of 5
    }
  },
  {
    timestamps: true,   // auto-manages createdAt & updatedAt — do NOT re-declare above
    collection: 'cards',
  }
);

// ── Indexes ───────────────────────────────────────────────────────────────────
// (bank_name indexed via index:true above — no explicit index needed)

// ── Hooks ─────────────────────────────────────────────────────────────────────


const Card = mongoose.model('Card', cardSchema);
module.exports = Card;
