/**
 * Auto-generated by SmartBank AI Codegen
 * Source: codegen/schemas/bank.schema.yaml
 * Entity: Bank
 * DO NOT EDIT MANUALLY — regenerate from YAML schema.
 */

const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const bankSchema = new mongoose.Schema(
  {
    bank_id: {
      type: String,
      unique: true,
      // External unique identifier (auto-generated UUID)
    },
    bank_name: {
      type: String,
      required: [true, 'bank_name is required'],
      unique: true,
      // Official bank name
    },
    minimum_balance: {
      type: Number,
      default: 0,
      min: 0,
      // Minimum account balance required in INR
    },
    interest_rate: {
      type: Number,
      min: 0,
      // Savings account interest rate (% p.a.)
    },
    forex_fee: {
      type: Number,
      min: 0,
      // Forex transaction fee (%)
    },
    account_types: {
      type: String,
      // Comma-separated account types (e.g. Savings,Current,Salary)
    },
    features: {
      type: String,
      // Comma-separated feature list (e.g. Zero Balance, Net Banking, UPI)
    },
    rating: {
      type: Number,
      min: 0,
      // Bank rating out of 5
    }
  },
  {
    timestamps: true,   // auto-manages createdAt & updatedAt — do NOT re-declare above
    collection: 'banks',
  }
);

// ── Indexes ───────────────────────────────────────────────────────────────────
// (bank_name is unique:true above — unique index already auto-created)

// ── Hooks ─────────────────────────────────────────────────────────────────────


const Bank = mongoose.model('Bank', bankSchema);
module.exports = Bank;
