/**
 * Auto-generated by SmartBank AI Codegen
 * Source: codegen/schemas/user.schema.yaml
 */

const User = require('./user.model');
const { UserInputError } = require('apollo-server-express');
const { updateUserSchema, validate } = require('./user.validation');

class UserService {

  // ── Get Profile ──────────────────────────────────────────────────────────────
  async getProfile(userId) {
    let user;
    if (userId === 'public') {
      user = await User.findOne({}); // Fallback to first user in system
    } else {
      user = await User.findById(userId).catch(() => null);
    }
    
    if (!user) throw new UserInputError('User not found.');
    return user;
  }

  // ── Get All Users ───────────────────────────────────────────────────────────
  async getAllUsers() {
    return User.find({}).sort({ createdAt: -1 });
  }

  // ── Get By ID ───────────────────────────────────────────────────────────────
  async getUserById(id) {
    const user = await User.findById(id);
    if (!user) throw new UserInputError('User not found.');
    return user;
  }

  // ── Update Profile ──────────────────────────────────────────────────────────
  async updateProfile(userId, input) {
    const { error } = validate(input, updateUserSchema);
    if (error) throw new UserInputError(error.details.map(d => d.message).join(', '));

    let user;
    if (userId === 'public') {
      user = await User.findOneAndUpdate({}, { $set: input }, { new: true, runValidators: true });
    } else {
      user = await User.findByIdAndUpdate(
        userId,
        { $set: input },
        { new: true, runValidators: true }
      ).catch(() => null);
    }

    if (!user) throw new UserInputError('User not found.');
    return user;
  }

  // ── Delete User ──────────────────────────────────────────────────────────────
  async deleteUser(id) {
    const user = await User.findByIdAndDelete(id);
    if (!user) throw new UserInputError('User not found.');
    return { success: true, message: `User ${user.email} deleted.` };
  }
}

module.exports = new UserService();
