/**
 * Auto-generated by SmartBank AI Codegen
 * Source: codegen/schemas/user.schema.yaml
 */

const mongoose = require('mongoose');

const userSchema = new mongoose.Schema(
  {
    user_id: {
      type: String,
      unique: true,
    },
    name: {
      type: String,
      required: [true, 'name is required'],
      minlength: 2,
      maxlength: 100,
    },
    email: {
      type: String,
      required: [true, 'email is required'],
      unique: true,
    },
    role: {
      type: String,
      enum: ["ADMIN","USER"],
      default: "USER",
    },
    salary: {
      type: Number,
      default: 0,
      min: 0,
    },
    profileType: {
      type: String,
      enum: ["STUDENT","WORKING_PROFESSIONAL","SELF_EMPLOYED","BUSINESS_OWNER","OTHER"],
      default: "OTHER",
    },
    isEmailVerified: {
      type: Boolean,
      default: false
    }
  },
  {
    timestamps: true,
    collection: 'users',
  }
);

const User = mongoose.model('User', userSchema);
module.exports = User;
