/**
 * Auto-generated by SmartBank AI Codegen
 * Source: codegen/schemas/user.schema.yaml
 * Test runner: Jest
 */

const mongoose = require('mongoose');
const { MongoMemoryServer } = require('mongodb-memory-server');
const User = require('./user.model');
const userService = require('./user.service');

let mongoServer;

beforeAll(async () => {
  mongoServer = await MongoMemoryServer.create();
  const uri = mongoServer.getUri();
  await mongoose.connect(uri);
});

afterAll(async () => {
  await mongoose.disconnect();
  await mongoServer.stop();
});

afterEach(async () => {
  await User.deleteMany({});
});

describe('UserService', () => {

  const validUser = {
    name: 'Test User',
    email: 'test@example.com',
    password: 'Password123!',
    role: 'USER',
    salary: 50000,
    profileType: 'Working Professional',
  };

  test('should register a new user and return token', async () => {
    const result = await userService.register(validUser);
    expect(result.token).toBeDefined();
    expect(result.user.email).toBe(validUser.email);
    expect(result.user.role).toBe('USER');
  });

  test('should not register duplicate email', async () => {
    await userService.register(validUser);
    await expect(userService.register(validUser)).rejects.toThrow();
  });

  test('should login with correct credentials', async () => {
    await userService.register(validUser);
    const result = await userService.login(validUser.email, validUser.password);
    expect(result.token).toBeDefined();
  });

  test('should reject login with wrong password', async () => {
    await userService.register(validUser);
    await expect(userService.login(validUser.email, 'wrongpassword')).rejects.toThrow();
  });

  test('should get user profile by ID', async () => {
    const { user } = await userService.register(validUser);
    const profile = await userService.getProfile(user._id);
    expect(profile.email).toBe(validUser.email);
  });

  test('should update user profile', async () => {
    const { user } = await userService.register(validUser);
    const updated = await userService.updateProfile(user._id, { name: 'Updated Name' });
    expect(updated.name).toBe('Updated Name');
  });

  test('should delete user', async () => {
    const { user } = await userService.register(validUser);
    const result = await userService.deleteUser(user._id);
    expect(result.success).toBe(true);
  });

});
