#!/usr/bin/env node
/**
 * backend/codegen/generator.js
 * 
 * Schema-driven module generator for SmartBank AI.
 * 
 * Usage:
 *   node codegen/generator.js codegen/schemas/user.schema.yaml
 * 
 * Reads a YAML schema file and generates:
 *   1. {entity}.model.js       — Mongoose model
 *   2. {entity}.validation.js  — Joi validation schemas
 *   3. {entity}.service.js     — Business logic
 *   4. {entity}.resolver.js    — GraphQL resolvers
 *   5. {entity}.test.js        — Jest unit tests
 *   6. MODULE.md               — Auto-generated documentation
 */

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

// ── CLI ───────────────────────────────────────────────────────────────────────

const schemaPath = process.argv[2];
if (!schemaPath) {
  console.error('❌  Usage: node codegen/generator.js codegen/schemas/{entity}.schema.yaml');
  process.exit(1);
}

const fullPath = path.resolve(__dirname, '..', schemaPath);
if (!fs.existsSync(fullPath)) {
  console.error(`❌  Schema file not found: ${fullPath}`);
  process.exit(1);
}

const schema = yaml.load(fs.readFileSync(fullPath, 'utf8'));
const entity = schema.entity;
const entityLower = entity.toLowerCase();
const moduleName = schema.module;
const outputDir = path.resolve(__dirname, '..', 'src', 'app-modules', moduleName);

if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

console.log(`\n🚀  Generating module: ${moduleName}`);
console.log(`📁  Output directory: ${outputDir}\n`);

// ── Helpers ───────────────────────────────────────────────────────────────────

const write = (filename, content) => {
  const filePath = path.join(outputDir, filename);
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`  ✅  Generated: ${filename}`);
};

const mongooseTypeMap = { String: 'String', Number: 'Number', Boolean: 'Boolean', Date: 'Date', ObjectId: 'mongoose.Schema.Types.ObjectId' };
const joiTypeMap = { String: 'Joi.string()', Number: 'Joi.number()', Boolean: 'Joi.boolean()', Date: 'Joi.date()' };
const graphqlTypeMap = { String: 'String', Number: 'Float', Boolean: 'Boolean', Date: 'String', ObjectId: 'ID' };

// ── 1. MODEL ──────────────────────────────────────────────────────────────────

const generateModel = () => {
  const fields = schema.fields.map(f => {
    const mongoType = mongooseTypeMap[f.type] || 'String';
    let def = `    ${f.name}: {
      type: ${mongoType}`;
    if (f.required) def += `,\n      required: [true, '${f.name} is required']`;
    if (f.unique) def += `,\n      unique: true`;
    if (f.enum) def += `,\n      enum: ${JSON.stringify(f.enum)}`;
    if (f.default !== undefined) def += `,\n      default: ${JSON.stringify(f.default)}`;
    if (f.minLength) def += `,\n      minlength: ${f.minLength}`;
    if (f.maxLength) def += `,\n      maxlength: ${f.maxLength}`;
    if (f.min !== undefined) def += `,\n      min: ${f.min}`;
    if (f.index && !f.unique) def += `,\n      index: true`;
    if (f.description) def += `,\n      // ${f.description}`;
    if (f.name === 'password') def += `,\n      select: false`;
    def += `\n    }`;
    return def;
  }).join(',\n');

  return `/**
 * Auto-generated by SmartBank AI Codegen
 * Source: ${schemaPath}
 * Entity: ${entity}
 * DO NOT EDIT MANUALLY — regenerate from YAML schema.
 */

const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const ${entityLower}Schema = new mongoose.Schema(
  {
${fields}
  },
  {
    timestamps: true,
    collection: '${schema.collection || entityLower + 's'}',
  }
);

// ── Indexes ───────────────────────────────────────────────────────────────────
${schema.fields.filter(f => f.index).map(f => `${entityLower}Schema.index({ ${f.name}: 1 });`).join('\n')}

// ── Hooks ─────────────────────────────────────────────────────────────────────
${entityLower === 'user' ? `
// Hash password before save
${entityLower}Schema.pre('save', async function (next) {
  if (!this.isModified('password')) return next();
  this.password = await bcrypt.hash(this.password, 12);
  next();
});

// Compare password method
${entityLower}Schema.methods.comparePassword = async function (candidatePassword) {
  return bcrypt.compare(candidatePassword, this.password);
};
` : ''}

const ${entity} = mongoose.model('${entity}', ${entityLower}Schema);
module.exports = ${entity};
`;
};

// ── 2. VALIDATION ─────────────────────────────────────────────────────────────

const generateValidation = () => {
  const joiFields = schema.fields
    .filter(f => !['createdAt', 'updatedAt'].includes(f.name) && f.name !== 'password')
    .map(f => {
      let joiDef = `  ${f.name}: ${joiTypeMap[f.type] || 'Joi.string()'}`;
      if (f.required) joiDef += '.required()';
      else joiDef += '.optional()';
      if (f.enum) joiDef += `.valid(${f.enum.map(e => `'${e}'`).join(', ')})`;
      if (f.minLength) joiDef += `.min(${f.minLength})`;
      if (f.maxLength) joiDef += `.max(${f.maxLength})`;
      if (f.min !== undefined) joiDef += `.min(${f.min})`;
      if (f.format === 'email') joiDef += `.email()`;
      return joiDef;
    }).join(',\n');

  return `/**
 * Auto-generated by SmartBank AI Codegen
 * Source: ${schemaPath}
 */

const Joi = require('joi');

const register${entity}Schema = Joi.object({
${joiFields},
  password: Joi.string().min(8).required(),
});

const login${entity}Schema = Joi.object({
  email: Joi.string().email().required(),
  password: Joi.string().required(),
});

const update${entity}Schema = Joi.object({
${joiFields},
});

const validate = (data, schema) => schema.validate(data, { abortEarly: false });

module.exports = { register${entity}Schema, login${entity}Schema, update${entity}Schema, validate };
`;
};

// ── 3. SERVICE ────────────────────────────────────────────────────────────────

const generateService = () => {
  return `/**
 * Auto-generated by SmartBank AI Codegen
 * Source: ${schemaPath}
 */

const ${entity} = require('./${entityLower}.model');
const { signToken } = require('../../shared/auth');
const { sendSystemNotification } = require('../../shared/notification');
const { UserInputError, AuthenticationError } = require('apollo-server-express');
const { register${entity}Schema, login${entity}Schema, update${entity}Schema, validate } = require('./${entityLower}.validation');
const { v4: uuidv4 } = require('uuid');

class ${entity}Service {

  // ── Register ────────────────────────────────────────────────────────────────
  async register(input) {
    const { error } = validate(input, register${entity}Schema);
    if (error) throw new UserInputError(error.details.map(d => d.message).join(', '));

    const existing = await ${entity}.findOne({ email: input.email });
    if (existing) throw new UserInputError('An account with this email already exists.');

    const user = await ${entity}.create({
      ...input,
      user_id: uuidv4(),
    });

    // Fire UserRegistered event
    await sendSystemNotification({
      to: user.email,
      name: user.name,
      title: 'Welcome to SmartBank AI!',
      message: 'Your account has been created successfully. Start exploring AI-powered banking features.',
    }).catch(err => console.error('[Notification] Email failed:', err.message));

    const token = signToken({ id: user._id, email: user.email, role: user.role });
    return { token, user };
  }

  // ── Login ───────────────────────────────────────────────────────────────────
  async login(email, password) {
    const { error } = validate({ email, password }, login${entity}Schema);
    if (error) throw new UserInputError(error.details[0].message);

    const user = await ${entity}.findOne({ email }).select('+password');
    if (!user) throw new AuthenticationError('Invalid email or password.');

    const isMatch = await user.comparePassword(password);
    if (!isMatch) throw new AuthenticationError('Invalid email or password.');

    const token = signToken({ id: user._id, email: user.email, role: user.role });
    return { token, user };
  }

  // ── Get Profile ──────────────────────────────────────────────────────────────
  async getProfile(userId) {
    const user = await ${entity}.findById(userId);
    if (!user) throw new UserInputError('User not found.');
    return user;
  }

  // ── Get All Users (Admin) ───────────────────────────────────────────────────
  async getAllUsers() {
    return ${entity}.find({}).sort({ createdAt: -1 });
  }

  // ── Get By ID (Admin) ───────────────────────────────────────────────────────
  async getUserById(id) {
    const user = await ${entity}.findById(id);
    if (!user) throw new UserInputError('User not found.');
    return user;
  }

  // ── Update Profile ──────────────────────────────────────────────────────────
  async updateProfile(userId, input) {
    const { error } = validate(input, update${entity}Schema);
    if (error) throw new UserInputError(error.details.map(d => d.message).join(', '));

    const user = await ${entity}.findByIdAndUpdate(
      userId,
      { $set: input },
      { new: true, runValidators: true }
    );
    if (!user) throw new UserInputError('User not found.');
    return user;
  }

  // ── Delete User (Admin) ──────────────────────────────────────────────────────
  async deleteUser(id) {
    const user = await ${entity}.findByIdAndDelete(id);
    if (!user) throw new UserInputError('User not found.');
    return { success: true, message: \`User \${user.email} deleted.\` };
  }
}

module.exports = new ${entity}Service();
`;
};

// ── 4. RESOLVER ───────────────────────────────────────────────────────────────

const generateResolver = () => {
  return `/**
 * Auto-generated by SmartBank AI Codegen
 * Source: ${schemaPath}
 */

const ${entityLower}Service = require('./${entityLower}.service');
const { requireAuth, requireAdmin } = require('../../shared/auth');

const ${entityLower}Resolvers = {
  Query: {
    getProfile: async (_, __, context) => {
      const user = requireAuth(context);
      return ${entityLower}Service.getProfile(user.id);
    },

    getAllUsers: async (_, __, context) => {
      requireAdmin(context);
      return ${entityLower}Service.getAllUsers();
    },

    getUserById: async (_, { id }, context) => {
      requireAdmin(context);
      return ${entityLower}Service.getUserById(id);
    },
  },

  Mutation: {
    registerUser: async (_, { input }) => {
      return ${entityLower}Service.register(input);
    },

    loginUser: async (_, { email, password }) => {
      return ${entityLower}Service.login(email, password);
    },

    updateProfile: async (_, { input }, context) => {
      const user = requireAuth(context);
      return ${entityLower}Service.updateProfile(user.id, input);
    },

    deleteUser: async (_, { id }, context) => {
      requireAdmin(context);
      return ${entityLower}Service.deleteUser(id);
    },
  },
};

module.exports = ${entityLower}Resolvers;
`;
};

// ── 5. GRAPHQL TYPE DEFS ──────────────────────────────────────────────────────

const generateTypeDefs = () => {
  const gqlFields = schema.fields
    .filter(f => f.name !== 'password')
    .map(f => {
      const gqlType = graphqlTypeMap[f.type] || 'String';
      const req = f.required || f.unique ? '!' : '';
      return `  ${f.name}: ${gqlType}${req}`;
    }).join('\n');

  return `# Auto-generated by SmartBank AI Codegen — Source: ${schemaPath}

type ${entity} {
  _id: ID!
  ${gqlFields}
  createdAt: String
  updatedAt: String
}

type ${entity}AuthPayload {
  token: String!
  user: ${entity}!
}

type DeleteResult {
  success: Boolean!
  message: String!
}

input Register${entity}Input {
${schema.fields.filter(f => !['createdAt','updatedAt','user_id','isEmailVerified'].includes(f.name)).map(f => {
    const gqlType = graphqlTypeMap[f.type] || 'String';
    const req = f.required ? '!' : '';
    return `  ${f.name}: ${gqlType}${req}`;
  }).join('\n')}
}

input Update${entity}Input {
${schema.fields.filter(f => !['createdAt','updatedAt','user_id','isEmailVerified','password','role'].includes(f.name)).map(f => {
    const gqlType = graphqlTypeMap[f.type] || 'String';
    return `  ${f.name}: ${gqlType}`;
  }).join('\n')}
}

type Query {
  getProfile: ${entity}
  getAllUsers: [${entity}]
  getUserById(id: ID!): ${entity}
}

type Mutation {
  registerUser(input: Register${entity}Input!): ${entity}AuthPayload!
  loginUser(email: String!, password: String!): ${entity}AuthPayload!
  updateProfile(input: Update${entity}Input!): ${entity}
  deleteUser(id: ID!): DeleteResult!
}
`;
};

// ── 6. TESTS ──────────────────────────────────────────────────────────────────

const generateTests = () => {
  return `/**
 * Auto-generated by SmartBank AI Codegen
 * Source: ${schemaPath}
 * Test runner: Jest
 */

const mongoose = require('mongoose');
const { MongoMemoryServer } = require('mongodb-memory-server');
const ${entity} = require('./${entityLower}.model');
const ${entityLower}Service = require('./${entityLower}.service');

let mongoServer;

beforeAll(async () => {
  mongoServer = await MongoMemoryServer.create();
  const uri = mongoServer.getUri();
  await mongoose.connect(uri);
});

afterAll(async () => {
  await mongoose.disconnect();
  await mongoServer.stop();
});

afterEach(async () => {
  await ${entity}.deleteMany({});
});

describe('${entity}Service', () => {

  const validUser = {
    name: 'Test User',
    email: 'test@example.com',
    password: 'Password123!',
    role: 'USER',
    salary: 50000,
    profileType: 'Working Professional',
  };

  test('should register a new user and return token', async () => {
    const result = await ${entityLower}Service.register(validUser);
    expect(result.token).toBeDefined();
    expect(result.user.email).toBe(validUser.email);
    expect(result.user.role).toBe('USER');
  });

  test('should not register duplicate email', async () => {
    await ${entityLower}Service.register(validUser);
    await expect(${entityLower}Service.register(validUser)).rejects.toThrow();
  });

  test('should login with correct credentials', async () => {
    await ${entityLower}Service.register(validUser);
    const result = await ${entityLower}Service.login(validUser.email, validUser.password);
    expect(result.token).toBeDefined();
  });

  test('should reject login with wrong password', async () => {
    await ${entityLower}Service.register(validUser);
    await expect(${entityLower}Service.login(validUser.email, 'wrongpassword')).rejects.toThrow();
  });

  test('should get user profile by ID', async () => {
    const { user } = await ${entityLower}Service.register(validUser);
    const profile = await ${entityLower}Service.getProfile(user._id);
    expect(profile.email).toBe(validUser.email);
  });

  test('should update user profile', async () => {
    const { user } = await ${entityLower}Service.register(validUser);
    const updated = await ${entityLower}Service.updateProfile(user._id, { name: 'Updated Name' });
    expect(updated.name).toBe('Updated Name');
  });

  test('should delete user', async () => {
    const { user } = await ${entityLower}Service.register(validUser);
    const result = await ${entityLower}Service.deleteUser(user._id);
    expect(result.success).toBe(true);
  });

});
`;
};

// ── 7. MODULE.md ─────────────────────────────────────────────────────────────

const generateModuleDoc = () => {
  const fields = schema.fields.map(f =>
    `| \`${f.name}\` | ${f.type} | ${f.required ? '✅' : '❌'} | ${f.unique ? '✅' : '❌'} | ${f.description || ''} |`
  ).join('\n');

  return `# ${moduleName} Module

> Auto-generated documentation from \`${schemaPath}\`
> **DO NOT EDIT MANUALLY** — regenerate from YAML schema.

## Entity: ${entity}

Collection: \`${schema.collection || entityLower + 's'}\`

## Fields

| Field | Type | Required | Unique | Description |
|-------|------|----------|--------|-------------|
${fields}

## Operations

### Queries
${(schema.operations?.queries || []).map(q => `- **\`${q.name}\`** (${q.auth}) — ${q.description || ''}`).join('\n')}

### Mutations
${(schema.operations?.mutations || []).map(m => `- **\`${m.name}\`** (${m.auth}) — ${m.description || ''}`).join('\n')}

## Permissions

| Role | Allowed Operations |
|------|--------------------|
${Object.entries(schema.permissions || {}).map(([role, ops]) => `| \`${role}\` | ${ops.join(', ')} |`).join('\n')}

## Events

${(schema.events || []).map(e => `- **\`${e.trigger}\`** → emits \`${e.emit}\`${e.notify ? ` + sends ${e.notify} notification` : ''}`).join('\n')}

## Generated Files

| File | Purpose |
|------|---------|
| \`${entityLower}.model.js\` | Mongoose schema + model |
| \`${entityLower}.validation.js\` | Joi input validation |
| \`${entityLower}.service.js\` | Business logic |
| \`${entityLower}.resolver.js\` | GraphQL resolvers |
| \`${entityLower}.graphql\` | GraphQL type definitions |
| \`${entityLower}.test.js\` | Jest unit tests |
`;
};

// ── RUN GENERATOR ────────────────────────────────────────────────────────────

write(`${entityLower}.model.js`, generateModel());
write(`${entityLower}.validation.js`, generateValidation());
write(`${entityLower}.service.js`, generateService());
write(`${entityLower}.resolver.js`, generateResolver());
write(`${entityLower}.graphql`, generateTypeDefs());
write(`${entityLower}.test.js`, generateTests());
write('MODULE.md', generateModuleDoc());

console.log(`\n✅  Module "${moduleName}" generated successfully!`);
console.log(`\nNext steps:`);
console.log(`  cd backend && npm install`);
console.log(`  npm test`);
console.log(`  npm run dev\n`);
