/**
 * Auto-generated by SmartBank AI Codegen
 * Source: codegen/schemas/investment.schema.yaml
 * Entity: Investment
 * DO NOT EDIT MANUALLY — regenerate from YAML schema.
 */

const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const investmentSchema = new mongoose.Schema(
  {
    investment_id: {
      type: String,
      unique: true,
      // External unique identifier (auto-generated UUID)
    },
    user_id: {
      type: String,
      required: [true, 'user_id is required'],
      index: true,
      // Reference to the owning user
    },
    investment_type: {
      type: String,
      required: [true, 'investment_type is required'],
      enum: ["stock","mutual_fund","fixed_deposit"],
      // Type of investment
    },
    amount: {
      type: Number,
      required: [true, 'amount is required'],
      min: 1,
      // Invested amount in INR
    },
    expected_return: {
      type: Number,
      min: 0,
      // Expected annual return percentage
    },
    current_value: {
      type: Number,
      min: 0,
      // Current market value of investment
    },
    status: {
      type: String,
      enum: ["active","closed","pending"],
      default: "active",
      // Investment status
    },
    invested_at: {
      type: Date,
      // Date investment was made
    },
    notes: {
      type: String,
      maxlength: 500,
      // Optional notes
    }
  },
  {
    timestamps: true,   // auto-manages createdAt & updatedAt — do NOT re-declare above
    collection: 'investments',
  }
);

// ── Indexes ───────────────────────────────────────────────────────────────────
// (user_id indexed via index:true above — no explicit index needed)

// ── Hooks ─────────────────────────────────────────────────────────────────────


const Investment = mongoose.model('Investment', investmentSchema);
module.exports = Investment;
