/**
 * Auto-generated by SmartBank AI Codegen
 * Source: codegen/schemas/expense.schema.yaml
 * Entity: Expense
 * DO NOT EDIT MANUALLY — regenerate from YAML schema.
 */

const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const expenseSchema = new mongoose.Schema(
  {
    expense_id: {
      type: String,
      unique: true,
      // External unique identifier (auto-generated UUID)
    },
    user_id: {
      type: String,
      required: [true, 'user_id is required'],
      index: true,
      // Reference to the owning user
    },
    category: {
      type: String,
      enum: ["food","travel","shopping","rent","other"],
      default: "other",
      // Expense category
    },
    amount: {
      type: Number,
      required: [true, 'amount is required'],
      min: 0,
      // Expense amount in INR
    },
    month: {
      type: String,
      // Month identifier in YYYY-MM format (e.g. 2026-03)
    },
    description: {
      type: String,
      maxlength: 300,
      // Optional expense description
    }
  },
  {
    timestamps: true,   // auto-manages createdAt & updatedAt — do NOT re-declare above
    collection: 'expenses',
  }
);

// ── Indexes ───────────────────────────────────────────────────────────────────
// (user_id indexed via index:true above — no explicit index needed)

// ── Hooks ─────────────────────────────────────────────────────────────────────


const Expense = mongoose.model('Expense', expenseSchema);
module.exports = Expense;
